on:
  workflow_call:

env:
  WORK_DIR: /__w/PandABlocks-FPGA/PandABlocks-FPGA

jobs:
  make_packages:
    strategy:
      fail-fast: false
      matrix:
        app: [
          "pandabox-no-fmc",
          "pandabox-fmc-24vio",
          "pandabox-fmc-acq427",
          "pandabox-fmc-acq430",
          "pandabox-fmc-lback-sfp-lback",
          "pandabrick",
          "xu5-st1-no-fmc",
          "xu5-st1-fmc-acq430"
          ]
    runs-on:
      group: iris_runners
    container:
      image: ghcr.io/pandablocks/pandablocks-ci-container:latest
      options: --privileged

    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: repos/PandABlocks-fpga
          fetch-depth: 0
          submodules: true

      - name: Checkout rootfs and Give Directory Perms
        uses: ./repos/PandABlocks-fpga/.github/actions/setupenv

      # Make ipks
      - name: build carrier_ip and ipks
        id: make_ipks
        run: |
          cd repos/PandABlocks-fpga
          ln -s CONFIG.example CONFIG
          make WORK_DIR=$WORK_DIR carrier_ip APP_NAME=${{ matrix.app }}
          tini -s -- make WORK_DIR=$WORK_DIR ipk APP_NAME=${{ matrix.app }}
          # Documentation is the same for all
          if [[ ${{ matrix.app }} = pandabox-no-fmc ]]; then
              tini -s -- make WORK_DIR=$WORK_DIR doc-ipk APP_NAME=${{ matrix.app }}
          fi

      # Artifacts
      - name: Upload ipk
        uses: actions/upload-artifact@v4
        with:
          name: ipks-${{ matrix.app }}
          path: /build/panda-fpga*.ipk
          if-no-files-found: error
