on:
  workflow_call:

env:
  WORK_DIR: /__w/PandABlocks-FPGA/PandABlocks-FPGA

jobs:
  make_zpkg:
    strategy:
      fail-fast: false
      matrix:
        app: [
          "PandABox-no-fmc",
          "PandABox-fmc_24vio",
          "PandABox-fmc_acq427",
          "PandABox-fmc_acq430",
          "PandABox-fmc_lback-sfp_lback",
          "PandABrick",
          "xu5_st1-no-fmc",
          "xu5_st1-fmc_acq430"
          ]
    runs-on:
      group: iris_runners
    container:
      image: ghcr.io/pandablocks/pandablocks-ci-container:latest
      options: --privileged

    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: repos/PandABlocks-fpga
          fetch-depth: 0
          submodules: true

      - name: Checkout rootfs and Give Directory Perms
        uses: ./repos/PandABlocks-fpga/.github/actions/setupenv

      # Make zpkgs
      - name: build carrier_ip and zpkg
        id: make_zpkg
        run: |
          cd repos/PandABlocks-fpga
          ln -s CONFIG.example CONFIG
          make WORK_DIR=$WORK_DIR carrier_ip APP_NAME=${{ matrix.app }}
          tini -s -- make WORK_DIR=$WORK_DIR zpkg APP_NAME=${{ matrix.app }}
          tini -s -- make WORK_DIR=$WORK_DIR ipk APP_NAME=${{ matrix.app }}
          # Documentation is the same for all
          if [[ ${{ matrix.app }} = PandABox-no-fmc ]]; then
              tini -s -- make WORK_DIR=$WORK_DIR doc-ipk APP_NAME=${{ matrix.app }}
          fi

      # Artifacts
      - name: Upload zpkg
        uses: actions/upload-artifact@v4
        with:
          name: zpkgs-${{ matrix.app }}
          path: /build/panda-fpga@*.zpg
          if-no-files-found: error

      - name: Upload ipk
        uses: actions/upload-artifact@v4
        with:
          name: ipks-${{ matrix.app }}
          path: /build/panda-fpga*.ipk
          if-no-files-found: error
