name: Docs CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  make_docs:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-fpga
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo apt-get install python3-sphinx python3-sphinx-rtd-theme
          sudo pip install matplotlib

      #CONFIG files
      - name: Generate fpga CONFIG files
        run: |
          sudo bash PandABlocks-fpga/.github/scripts/config-file-fpga.sh
          cat PandABlocks-fpga/CONFIG

      # Build docs
      - name: Make docs
        run: |
          cd PandABlocks-fpga
          make docs

      # Publish docs
      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{ github.ref }}
          split-by: /
      
      - name: Move to versioned directory
        # e.g. master or 0.1.2
        run: |
          mkdir PandABlocks-fpga/.github/pages
          mv build/html "PandABlocks-fpga/.github/pages/${{ steps.split.outputs._2 }}"

      - name: Publish Docs to gh-pages
        # Only master and tags are published
        if: "${{ github.repository_owner == 'dls-controls' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}"
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PandABlocks-fpga/.github/pages
          keep_files: true
